/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceAiRouteImport } from './routes/voice-ai'
import { Route as TrustCircleRouteImport } from './routes/trust-circle'
import { Route as SosRouteImport } from './routes/sos'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MapRouteImport } from './routes/map'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HelpCentersRouteImport } from './routes/help-centers'
import { Route as FakeCallRouteImport } from './routes/fake-call'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as AudioCaptureRouteImport } from './routes/audio-capture'
import { Route as AlertHistoryRouteImport } from './routes/alert-history'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const VoiceAiRoute = VoiceAiRouteImport.update({
  id: '/voice-ai',
  path: '/voice-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustCircleRoute = TrustCircleRouteImport.update({
  id: '/trust-circle',
  path: '/trust-circle',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpCentersRoute = HelpCentersRouteImport.update({
  id: '/help-centers',
  path: '/help-centers',
  getParentRoute: () => rootRouteImport,
} as any)
const FakeCallRoute = FakeCallRouteImport.update({
  id: '/fake-call',
  path: '/fake-call',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioCaptureRoute = AudioCaptureRouteImport.update({
  id: '/audio-capture',
  path: '/audio-capture',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertHistoryRoute = AlertHistoryRouteImport.update({
  id: '/alert-history',
  path: '/alert-history',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alert-history': typeof AlertHistoryRoute
  '/audio-capture': typeof AudioCaptureRoute
  '/contacts': typeof ContactsRoute
  '/fake-call': typeof FakeCallRoute
  '/help-centers': typeof HelpCentersRoute
  '/home': typeof HomeRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/sos': typeof SosRoute
  '/trust-circle': typeof TrustCircleRoute
  '/voice-ai': typeof VoiceAiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alert-history': typeof AlertHistoryRoute
  '/audio-capture': typeof AudioCaptureRoute
  '/contacts': typeof ContactsRoute
  '/fake-call': typeof FakeCallRoute
  '/help-centers': typeof HelpCentersRoute
  '/home': typeof HomeRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/sos': typeof SosRoute
  '/trust-circle': typeof TrustCircleRoute
  '/voice-ai': typeof VoiceAiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alert-history': typeof AlertHistoryRoute
  '/audio-capture': typeof AudioCaptureRoute
  '/contacts': typeof ContactsRoute
  '/fake-call': typeof FakeCallRoute
  '/help-centers': typeof HelpCentersRoute
  '/home': typeof HomeRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/sos': typeof SosRoute
  '/trust-circle': typeof TrustCircleRoute
  '/voice-ai': typeof VoiceAiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alert-history'
    | '/audio-capture'
    | '/contacts'
    | '/fake-call'
    | '/help-centers'
    | '/home'
    | '/map'
    | '/profile'
    | '/sos'
    | '/trust-circle'
    | '/voice-ai'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alert-history'
    | '/audio-capture'
    | '/contacts'
    | '/fake-call'
    | '/help-centers'
    | '/home'
    | '/map'
    | '/profile'
    | '/sos'
    | '/trust-circle'
    | '/voice-ai'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alert-history'
    | '/audio-capture'
    | '/contacts'
    | '/fake-call'
    | '/help-centers'
    | '/home'
    | '/map'
    | '/profile'
    | '/sos'
    | '/trust-circle'
    | '/voice-ai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AlertHistoryRoute: typeof AlertHistoryRoute
  AudioCaptureRoute: typeof AudioCaptureRoute
  ContactsRoute: typeof ContactsRoute
  FakeCallRoute: typeof FakeCallRoute
  HelpCentersRoute: typeof HelpCentersRoute
  HomeRoute: typeof HomeRoute
  MapRoute: typeof MapRoute
  ProfileRoute: typeof ProfileRoute
  SosRoute: typeof SosRoute
  TrustCircleRoute: typeof TrustCircleRoute
  VoiceAiRoute: typeof VoiceAiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice-ai': {
      id: '/voice-ai'
      path: '/voice-ai'
      fullPath: '/voice-ai'
      preLoaderRoute: typeof VoiceAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust-circle': {
      id: '/trust-circle'
      path: '/trust-circle'
      fullPath: '/trust-circle'
      preLoaderRoute: typeof TrustCircleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-centers': {
      id: '/help-centers'
      path: '/help-centers'
      fullPath: '/help-centers'
      preLoaderRoute: typeof HelpCentersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fake-call': {
      id: '/fake-call'
      path: '/fake-call'
      fullPath: '/fake-call'
      preLoaderRoute: typeof FakeCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio-capture': {
      id: '/audio-capture'
      path: '/audio-capture'
      fullPath: '/audio-capture'
      preLoaderRoute: typeof AudioCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alert-history': {
      id: '/alert-history'
      path: '/alert-history'
      fullPath: '/alert-history'
      preLoaderRoute: typeof AlertHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AlertHistoryRoute: AlertHistoryRoute,
  AudioCaptureRoute: AudioCaptureRoute,
  ContactsRoute: ContactsRoute,
  FakeCallRoute: FakeCallRoute,
  HelpCentersRoute: HelpCentersRoute,
  HomeRoute: HomeRoute,
  MapRoute: MapRoute,
  ProfileRoute: ProfileRoute,
  SosRoute: SosRoute,
  TrustCircleRoute: TrustCircleRoute,
  VoiceAiRoute: VoiceAiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
